### ISSUE TITLE
Support CLion 2020.3 EAP

### ISSUE THREAD

**Issue by ozkriff** [ron-rs/intellij-ron#3]
> Plugin error: Plugin 'RON' (version '1.3') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is CL-203.3645.37

**Comment by pkarakal** [comment]
this isn't working with 2020.3 release. Any  update?

**Comment by Puciek** [comment]
2020.3 is now the main release, so an update to make it work again with mainstream would be great :D

**Comment by JonahHenriksson** [comment]
I don't have access to CLion. If someone would like to look into this or confirm it is working that would be a great help. I am quite busy with school right now so I can't dedicate much time to this project.

**Comment by madwareru** [comment]
@JonahHenriksson Please take a look at this PR https://github.com/ron-rs/intellij-ron/pull/6
It seems to solve this issue

**Comment by madwareru** [comment]
It seems that we are stuck here for some time.

I had mixed feelings on this so I borrowed parser and lexer, modified them to suit my needs and made my own plugin with all issues presented here fixed: [RON Extended Support on marketplace](https://plugins.jetbrains.com/plugin/15878-ron-extended-support)

Among other things it has these features:
 - Code folding
 - Structural bracket matching
 - Basic autocompletion for options and extensions
 - Semantic highlighting to differentiate object "keys" and names
 - Color settings where you could customize highliting to better suit your experience

Please don't get this as an advertisement of my plugin, I just wanted to solve problems of people as soon as possible

**Comment by madwareru** [comment]
I don't mind if Johan merge all sourcecode back to intellij-ron from my repo and makes me co-maintainer, this way we won't have a mess with a choice which plugin user has to install

**Comment by JonahHenriksson** [comment]
Sorry for not paying much attention to this. I'm fine with merging your code, just need to test to see if it works on my platform.

**Comment by JonahHenriksson** [comment]
OK, just verified it works, and there aren't any big changes in the code, so I'll merge it and update the plugin. Sorry that it took so long that you had to make a new plugin. I don't want to be the cause for any redundancy in the marketplace. Let me know if the update fixes this issue.

**Comment by JonahPlusPlus** [comment]
Oh yeah, I'll make sure to add you as co-maintainer, it would be good to have someone who is more active with RON on this.

**Comment by JonahPlusPlus** [comment]
Alright, had some trouble getting it to build, but I updated my Java and IDE and got it to work. I uploaded it, and is currently under review. I also sent @madwareru a invite to be a maintainer, so that way there will be a greater chance of someone available to work on this.
