### ISSUE TITLE
`@import` not work

### ISSUE THREAD

**Issue by UkonnRa** [ron-rs/intellij-ron#5]
**Problem**

In the example of amethyst, lots of ron files are commenting the type info like:

```
/*!
    @import /amethyst_rendy/src/sprite/mod.rs#Sprites
    Sprites
*/

List((
    texture_width: 8,
    texture_height: 16,
    sprites: [
        (
            x: 0,
            y: 0,
            width: 4,
            height: 16,
        ),
        (
            x: 4,
            y: 0,
            width: 4,
            height: 4,
        ),
    ],
))
```

But there are no type hints shown in intellij-ron

**Comment by JonahHenriksson** [comment]
That is a format defined by another plugin. I am not sure that I want to add that format since it is not in the RON specs. I would like to see that become part of the official format before I add it. I'll close this for now.
